---
title: "Data Scienc"
author: "Chia-Ching Chou"
date: "November 23, 2014"
output:
  html_document:
    keep_md: yes
---
Prediction Assignment Writeup

#




```{r}
library(caret)
#read trainning data and remove missing values
inTrainData <- read.csv("pml-training.csv",na.strings=c("NA",""))
missingVals<-apply(inTrainData,2, function (x) {sum (is.na(x))})
tr_temp<-inTrainData[,missingVals==0]
trainDataFull<-tr_temp[,-(1:7)]
#data splitting with 70% for traning data and 30% for cross validation.
inTrain<-createDataPartition(y=trainDataFull$classe,p=0.7,list=FALSE)
trainData<-trainDataFull[inTrain,]
cvData<-trainDataFull[-inTrain,]

```



```{r}
modelFit<-train(trainData[,-53],trainData$classe,method="rf",trControl=trainControl(method="oob",number=4,allowParallel=TRUE))
modelFit
```

```{r}
cv_predictions<-predict(modelFit,cvData[,-53])
confusionMatrix(cv_predictions,cvData$classe)
```

```{r}
pmlTest <- read.csv("pml-testing.csv", na.strings=c("NA",""))
testData<-pmlTest[,names(pmlTest)%in%names(trainDataFull)]
predictions<-predict(modelFit,testData)
predictions
```



